[env]
TERM = "screen-256color"

[font]
size = 12

# [font.bold]
# style = "Bold"

# to install the themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.9
dynamic_padding = true

[window.padding]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["--cd", "~"]




